server:
  port: 18080
spring:
  datasource:
    url: jdbc:mysql://192.168.200.188:3306/dubbo-demo?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-provider
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS

dubbo: #配置Dubbo  配置Dubbo协议   配置注册中心  配置包扫描(需要创建哪些Dubbo服务)
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://192.168.200.188:8848
  scan:
    base-packages: cn.itcast.user.service

