server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://192.168.200.188:3306/dubbo-demo?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level: 
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS