server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://192.168.200.188:3306/dubbo-demo?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: 192.168.200.188:8848
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS

dubbo: #配置dubbo  配置注册中心
  registry:
    address: spring-cloud://192.168.200.188
  consumer:
    check: false
    retries: 0